CREATE TABLE IF NOT EXISTS todo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS event (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  start DATETIME NOT NULL,
  end DATETIME NOT NULL
);

INSERT INTO todo (title, completed) VALUES ('First TODO', FALSE);
INSERT INTO event (title, start, end) VALUES ('Meeting', '2023-10-01 10:00:00', '2023-10-01 11:00:00');