name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Generate Prisma client
      run: npx prisma generate
    - name: Install wait-on utility
      run: npm install -g wait-on
    - name: Build Next.js application
      run: npm run build
      env:
        DATABASE_URL: mysql://fakeuser:fakepassword@localhost:3306/test_db
    - name: Start Next.js server
      run: npm run start & npx wait-on http://localhost:3000
      env:
        DATABASE_URL: mysql://fakeuser:fakepassword@localhost:3306/test_db
      timeout-minutes: 2
    - name: Run Playwright tests
      run: npx playwright test
      env:
        DATABASE_URL: mysql://fakeuser:fakepassword@localhost:3306/test_db
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
